### ISSUE TITLE
Bulk connecting switch interfaces.

### ISSUE THREAD

**Issue by ldyte3** [tiffanykaczmarek/netbox-bulk-connect#1]
I need to bulk connect lots of ports e.g. 24 ports from a patch panel to 24 ports/interface of a switch (port 1 on patch panel to port 2 switch, port 2 patch to port 4 switch etc). The problem is no device (the switch interfaces i want to bulk connect to) / switches show up in device b.

Would it be possible to add support for switch interfaces for the bulk connecting process.

**Comment by pupeno** [comment]
This is something that we need at Wifinity and we started working on this. I hope we'll have a PR soon.

**Comment by sombra-taras-govda** [comment]
Hello, just added pull request that resolves this issue.
